#!/bin/bash

# Save this file as /usr/bin/apt-get and chmod +x it.
# This code is open source, based on apt-pac by cookiengineer

cwd=${0%%/apt-get} # figure out where this script is being run from
# (this way it doesn't error out if it's not run from the directory it's in)

if [[ -f /usr/local/bin/apt ]]; then
    /usr/local/bin/apt $@
elif [[ -f $cwd/apt ]]; then
    $cwd/apt $@
else
    echo "Error: apt-pacman-wrapper is not installed properly."
    echo "Please see https://github.com/kreismit/apt-pacman-wrapper"
    exit 1
fi
